server_name: $SERVER_NAME

host: $NATS_HOST
port: $NATS_PORT

http_port: $NATS_HTTP_PORT

authorization {
  token: $NATS_AUTH_TOKEN
}

jetstream {
  store_dir: $JETSTREAM_STORE_DIR
}

cluster {
  name: $CLUSTER_NAME
  listen: $NATS_CLUSTER_LISTEN
  authorization {
    user: $NATS_CLUSTER_AUTH_USER
    password: $NATS_CLUSTER_AUTH_PASSWORD
  }
  routes = [
    $CLUSTER_ROUTES_SEED_PRIMARY
    $CLUSTER_ROUTES_SEED_SECONDARY
  ]
}
